services:
  db:
    image: mysql:8.0
    container_name: transit_traces_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transit_traces
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: transit_traces_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
